### PR TITLE
Adding support for msgpack.

### PR DESCRIPTION
**Pull request by cgore**

### CODE REVIEW

**Comment by cgore** [comment]
As a question, there's lots of things in Clojure that don't really work in msgpack: keywords, ratios, etc.  Would it make more sense to have that handled by the middleware, or would it make more sense to expect the endpoints to ensure there isn't anything weird in their response hash map?  Basically, should a function like:
```clojure

(defn clean-hash-map [h]
  (stringify-keys (postwalk #(cond (keyword? %) (name %)
                                   (ratio? %) (double %)
                                   ;; ... other things ...
                                   :else %)
                            h)))
```
Be:
- integrated into the middleware itself?
- a library function available in the middleware?
- written by each user?

**Comment by ikitommi** [comment]
I think there should be a protocol for it, having a serialize and coerce functions to provide symmetry + implementation for all the common classes/records. Serialize should be called by the RMF-middlewares and coercion by the web lib, based on a) the request encoding and b) the given input schema.

For example, In the next version of the compojure-api, the coercion matcher be selected based on those two, giving nice and transparent support.

Do you want to write all the coercion rules?

**Comment by cgore** [comment]
Yeah, that makes sense, but the more that I'm thinking about it that protocol should probably live in clojure-msgpack itself, not in the middleware.

**Comment by cgore** [comment]
We've been using a private branch with these incomplete changes on it, and ran into an encoding issue which is fixed here.  I'm not sure if we need to change the decode too, I'm going to look into that.

**Comment by cgore** [comment]
We've also broken out a `:msgpack-kw` that keywordizes the result, along the same style as `:json-kw`.

**Comment by cgore** [comment]
I've changed over the style used for decoding to be a streaming operation too now.

**Comment by cgore** [comment]
I think this should resolve the issue with the weird string handling from slurp/spit.  We saw it when we tried accessing the service using this via a Python script.

I'm thinking that remapping we talked about above doesn't really belong here, and is probably a completely separate thing, so I'm not thinking it should be part of the PR therefore.

Does this look like it needs anything more to you?

**Comment by Deraen** [comment]
I have no plans to doing more releases of this fork but you can either send PR to the upstream project or I can apply this there myself.

Either way there is one thing I don't like about this: `com.google.guava/guava` dependency adds 2MB to every project which depends on r-m-f and I'm not even sure if it's used at all?

**Comment by cgore** [comment]
I removed the guava reference, it wasn't being used at all, thanks.

So the ngrunwald version is back alive again then?

**Comment by Deraen** [comment]
Yeah, I'm maintaining it now. It's not yet used on Compojure-api as there's still difference in middleware option format (options map vs. keyword args) which I should probably solve as soon as possible, but unfortunately I'm quite busy currently.

**Comment by cgore** [comment]
Cool, I've actually got an existing PR there at https://github.com/ngrunwald/ring-middleware-format/pull/45 to do this, and then it just sat there so I made this one.  I can roll all of these onto that then if that seems best.

**Comment by cgore** [comment]
Is your plan to make the middleware option format work like it does originally over there on ngrunwald, or like it does over here on metosin?

**Comment by Deraen** [comment]
Eventually, like it works here but for now ngrunwald still uses keyword arguments. I feel strongly that using proper map is nearly always preferred over keyword arguments.

Would be cool if you could update PR there to match this.

**Comment by cgore** [comment]
Okay, I'll do that then.

**Comment by cgore** [comment]
Everything should match up over on https://github.com/ngrunwald/ring-middleware-format/pull/45 now.

Are you wanting the keyword-args -> map changeover before the ngrunwald library would be used in compojure-api to replace this one, or are you planning on switching it out before that?  Is there anything else major before compojure-api would get switched over to the ngrunwald repo besides that?

**Comment by Deraen** [comment]
This was merged upstream.

**Pull request closed without merging**
